apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fgs2oy11d-nodejs
  janus-idp.io/tekton: fgs2oy11d-nodejs
  backstage.io/kubernetes-id: fgs2oy11d-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fgs2oy11d-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
