apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fgs2oy11d-nodejs-gitops
  description: This is GitOps manifest for fgs2oy11d-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=fgs2oy11d-nodejs
    backstage.io/kubernetes-id: fgs2oy11d-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: fgs2oy11d-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:fgs2oy11d-nodejs
